# Generated by Django 4.0.4 on 2022-07-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='credcricao',
            new_name='descricao',
        ),
    ]
